// Generated by CoffeeScript 1.10.0
(function() {
  var wxd;

  wxd = {};

  wxd.text = "<xml><ToUserName><![CDATA[123456789]]></ToUserName>\n<FromUserName><![CDATA[123456789]]></FromUserName>\n<CreateTime>1446015538</CreateTime>\n<MsgType><![CDATA[text]]></MsgType>\n<Content><![CDATA[test]]></Content>\n<MsgId>6210589445618122032</MsgId>\n</xml>";

  wxd.pic = "<xml><ToUserName><![CDATA[123456789]]></ToUserName>\n<FromUserName><![CDATA[123456789]]></FromUserName>\n<CreateTime>1446011712</CreateTime>\n<MsgType><![CDATA[image]]></MsgType>\n<PicUrl><![CDATA[http://mmbiz.qpic.cn/mmbiz/atysXcolaDLkNElNrqEhfEfPbQGLpICcAvKja6N0l7u1w\nshWJV4kzV6Hq1jqs2hTxbibcnQWh0YARia3mcv8H8XQ/0]]></PicUrl>\n<MsgId>6210573013073246036</MsgId>\n<MediaId><![CDATA[eoid8xZu1VK4E8XlZExXk8otXXzxDEUC4XpnmVMX1o_-082Be7wYXac6q0JDx5-G]]></Me\ndiaId>\n</xml>";

  module.exports = wxd;

}).call(this);
